spring:
  profiles:
    active: @environment@

---

spring:
  profiles: dev
  application:
    name: springcloud-server-config-dev

---

spring:
  profiles: test
  application:
    name: springcloud-server-config-test