spring:
  profiles:
    active: 
      - dev

---

spring:
  profiles: dev
  application:
    name: springcloud-server-config-dev

---

spring:
  profiles: test
  application:
    name: springcloud-server-config-test